### ISSUE TITLE
Add to Ultralisp ?

### ISSUE THREAD

**Issue by vindarel** [m-n/rundown#1]
Hey, this project and its dependencies are pretty cool. Would you like to add them to Quicklisp, or at least Ultralisp ? It's two clicks away. 

Regards

http://ultralisp.org/

**Comment by m-n** [comment]
Thanks for the interest. I'm not necessarily opposed to the idea but I'm hesitant for a few reasons. 

I don't use Common Lisp much any more -- I haven't touched most of these repos for ~4 years. Also, I left some sharp edges on `lazy-susan`, I probably wouldn't recommend it for general use. 

I'm not sure that the idea of repl-runnable markdown tutorials turned out to be generally useful. I haven't created any beyond the included `git-bisect` tutorial.

**Comment by vindarel** [comment]
Thanks for the context.

Be welcome back to CL when you want :)
